ALTER TABLE TB_MATRICULA_CURSO
ADD IC_ORIGEM CHAR(1)
GO
ALTER TABLE TB_HISTORICO_SIT_MATRICULA
ADD IC_ORIGEM CHAR(1)
GO


ALTER PROCEDURE [dbo].[SP_REL_MAT_CANC_CURSO]
	@DT_INICIO	VARCHAR(20)		,
	@DT_FIM		VARCHAR(20)		,
	@IC_TIPO	CHAR(1)		,
	@CURSOS		VARCHAR(2000)	,
	@IC_ORDENACAO	VARCHAR(10)	,
	@CD_SIT_MATRICULA1 VARCHAR(10) = NULL,
	@CD_SIT_MATRICULA2 VARCHAR(10) = NULL,
	@IC_ORIGEM1 VARCHAR(1)	= NULL,
	@IC_ORIGEM2 VARCHAR(1)	= NULL

AS

SET NOCOUNT ON

IF @CD_SIT_MATRICULA1 IS NULL
	SELECT @CD_SIT_MATRICULA1 = 'NO', @CD_SIT_MATRICULA2 = 'CA'
IF @IC_ORIGEM1 IS NULL
	SELECT @IC_ORIGEM1 = 'C', @IC_ORIGEM2 = 'I'

IF @IC_TIPO = 'A' 
BEGIN
	EXEC
	(
	'SELECT ' +
		'T1.DESCR_CURSO				AS ''Curso''		, ' +
		'RIGHT(''0'' + CONVERT(VARCHAR, T2.CD_CATEGORIA), 2) + ''/'' + RIGHT(''000'' + CONVERT(VARCHAR, T2.CD_MATRICULA), 4) AS ''Titulo'', ' +
		'T2.NOME_PESSOA				AS ''Pessoa''		, ' +
		'T3.DT_HISTORICO_SIT_MATRICULA   	AS ''DtSituacao''	, ' +
		'CASE T3.CD_HISTORICO_SIT_MATRICULA  ' +
		'WHEN ''NO'' THEN ''NORMAL'' ' +
		'WHEN ''CA'' THEN ''CANCELADA'' ' +
		'END					AS ''Situacao'',  ' +
		'T3.USER_ACESSO_SISTEMA AS "Usuario",  ' +
		'CASE T3.IC_ORIGEM  ' +
		'WHEN ''I'' THEN ''INTERNET'' ' +
		'ELSE ''CLUBE'' ' +
		'END					AS ''Origem''  ' +
	'FROM ' +
		'TB_CURSO			T1, ' +
		'TB_PESSOA			T2, ' +
		'TB_HISTORICO_SIT_MATRICULA	T3, ' +
		'TB_TURMA			T4  ' +
	'WHERE ' +
		'T1.CD_CURSO			= T4.CD_CURSO		AND ' +
		'T2.CD_MATRICULA		= T3.CD_MATRICULA	AND ' +
		'T2.SEQ_DEPENDENTE		= T3.SEQ_DEPENDENTE	AND ' +

		'T2.CD_CATEGORIA		= T3.CD_CATEGORIA	AND ' +
		'T3.SEQ_TURMA			= T4.SEQ_TURMA		AND ' +
		'T3.DT_HISTORICO_SIT_MATRICULA 	>= ''' + @DT_INICIO + ''' AND ' +
		'T3.DT_HISTORICO_SIT_MATRICULA 	<= ''' + @DT_FIM    + ''' AND ' +
		'(T3.CD_HISTORICO_SIT_MATRICULA = ''' + @CD_SIT_MATRICULA1 + ''' OR ' +
		'T3.CD_HISTORICO_SIT_MATRICULA = ''' + @CD_SIT_MATRICULA2 + ''') AND ' +
		'(ISNULL(T3.IC_ORIGEM, ''C'') = ''' + @IC_ORIGEM1 + ''' OR ' +
		'ISNULL(T3.IC_ORIGEM, ''C'') = ''' + @IC_ORIGEM2 + ''') AND ' +
		'T1.CD_CURSO			IN ' + @CURSOS + ' ' +
	'ORDER BY 1, ' + @IC_ORDENACAO
	)
END
ELSE
BEGIN
	CREATE TABLE #TB_RESULTADO
		(
		CD_CURSO	SMALLINT	,
		QT_MATRICULA	SMALLINT	,
		QT_CANCELAMENTO	SMALLINT
		)

	INSERT INTO
		#TB_RESULTADO
	SELECT
		CD_CURSO, 0, 0
	FROM
		TB_CURSO

	-- **************************************
	-- ATUALIZANDO A QUANTIDADE DE MATRICULAS
	-- **************************************
	SELECT
		T3.CD_CURSO		,
		COUNT(*) AS QUANTIDADE
	INTO
		#TB_TMP01
	FROM
		TB_HISTORICO_SIT_MATRICULA	T1,
		TB_TURMA			T2,

		TB_CURSO			T3
	WHERE
		T1.SEQ_TURMA			= T2.SEQ_TURMA	AND
		T2.CD_CURSO			= T3.CD_CURSO	AND
		T1.CD_HISTORICO_SIT_MATRICULA	= 'NO'		AND
		T1.DT_HISTORICO_SIT_MATRICULA 	>= CONVERT(DATETIME,@DT_INICIO)	AND
		T1.DT_HISTORICO_SIT_MATRICULA 	<= CONVERT(DATETIME,@DT_FIM) AND
		(ISNULL(T1.IC_ORIGEM, 'C') = @IC_ORIGEM1 OR 
		ISNULL(T1.IC_ORIGEM, 'C') = @IC_ORIGEM2)
		
	GROUP BY
		T3.CD_CURSO


	UPDATE
		#TB_RESULTADO
	SET

		QT_MATRICULA = QUANTIDADE
	FROM
		#TB_RESULTADO	T1,
		#TB_TMP01	T2
	WHERE	
		T1.CD_CURSO	= T2.CD_CURSO


	-- *****************************************
	-- ATUALIZANDO A QUANTIDADE DE CANCELAMENTOS
	-- *****************************************
	SELECT
		T3.CD_CURSO		,
		COUNT(*) AS QUANTIDADE
	INTO
		#TB_TMP02
	FROM
		TB_HISTORICO_SIT_MATRICULA	T1,
		TB_TURMA			T2,

		TB_CURSO			T3

	WHERE
		T1.SEQ_TURMA			= T2.SEQ_TURMA	AND
		T2.CD_CURSO			= T3.CD_CURSO	AND
		T1.CD_HISTORICO_SIT_MATRICULA	= 'CA'		AND
		T1.DT_HISTORICO_SIT_MATRICULA 	>= CONVERT(DATETIME,@DT_INICIO)	AND
		T1.DT_HISTORICO_SIT_MATRICULA	<= CONVERT(DATETIME,@DT_FIM) AND
		(ISNULL(T1.IC_ORIGEM, 'C') = @IC_ORIGEM1 OR 
		ISNULL(T1.IC_ORIGEM, 'C') = @IC_ORIGEM2)

	GROUP BY
		T3.CD_CURSO

	UPDATE
		#TB_RESULTADO
	SET
		QT_CANCELAMENTO = QUANTIDADE
	FROM
		#TB_RESULTADO	T1,
		#TB_TMP02	T2
	WHERE	
		T1.CD_CURSO	= T2.CD_CURSO

	EXEC
		(
	'SELECT ' +
		'T1.DESCR_CURSO		AS "Curso"	, ' +

		'T2.QT_MATRICULA	AS "Qt.Mat."	, ' +
		'T2.QT_CANCELAMENTO	AS "Qt.Canc." ' +
	'FROM  ' +
		'TB_CURSO	T1	, ' +
		'#TB_RESULTADO	T2 ' +
	'WHERE ' +
		'T1.CD_CURSO = T2.CD_CURSO AND ' +
		'T1.CD_CURSO IN ' + @CURSOS + ' ' +
	'ORDER BY ' + 
		'1'
		) 
END

go


INSERT INTO TB_Cadastro_Aplicacao
VALUES (3200, 'Cad. Local Academia')
INSERT INTO TB_Cadastro_Aplicacao
VALUES (3201, 'Incluir Local Academia')
INSERT INTO TB_Cadastro_Aplicacao
VALUES (3202, 'Alterar Local Academia')
INSERT INTO TB_Cadastro_Aplicacao
VALUES (3203, 'Excluir Local Academia')


INSERT INTO TB_Cadastro_Aplicacao
VALUES (3210, 'Cad. Servico Academia')
INSERT INTO TB_Cadastro_Aplicacao
VALUES (3211, 'Incluir Servico Academia')
INSERT INTO TB_Cadastro_Aplicacao
VALUES (3212, 'Alterar Servico Academia')
INSERT INTO TB_Cadastro_Aplicacao
VALUES (3213, 'Excluir Servico Academia')


INSERT INTO TB_Cadastro_Aplicacao
VALUES (3215, 'Inc Prof Serv Acad')
INSERT INTO TB_Cadastro_Aplicacao
VALUES (3216, 'Alt Prof Serv Acad')
INSERT INTO TB_Cadastro_Aplicacao
VALUES (3217, 'Exc Prof Serv Acad')
go



INSERT INTO TB_Aplicacao_Por_Grupo VALUES(3200, 1)
INSERT INTO TB_Aplicacao_Por_Grupo VALUES(3201, 1)
INSERT INTO TB_Aplicacao_Por_Grupo VALUES(3202, 1)
INSERT INTO TB_Aplicacao_Por_Grupo VALUES(3203, 1)
INSERT INTO TB_Aplicacao_Por_Grupo VALUES(3210, 1)
INSERT INTO TB_Aplicacao_Por_Grupo VALUES(3211, 1)
INSERT INTO TB_Aplicacao_Por_Grupo VALUES(3212, 1)
INSERT INTO TB_Aplicacao_Por_Grupo VALUES(3213, 1)
INSERT INTO TB_Aplicacao_Por_Grupo VALUES(3215, 1)
INSERT INTO TB_Aplicacao_Por_Grupo VALUES(3216, 1)
INSERT INTO TB_Aplicacao_Por_Grupo VALUES(3217, 1)
GO

CREATE TABLE TB_LOCAL_ACADEMIA
	(
	CD_LOCAL SMALLINT NOT NULL IDENTITY PRIMARY KEY,
	DESCR_LOCAL VARCHAR(30) NOT NULL
	)

GO

USE [iate]
GO
/****** Object:  StoredProcedure [dbo].[SP_ATUALIZA_MATRICULA]    Script Date: 03/19/2014 20:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/****** Object:  Stored Procedure dbo.SP_ATUALIZA_MATRICULA    Script Date: 04/08/03 21:22:12 ******/
/****** Object:  Stored Procedure dbo.SP_ATUALIZA_MATRICULA    Script Date: 13/11/2000 21:21:03 ******/
/****** Object:  Stored Procedure dbo.SP_ATUALIZA_MATRICULA    Script Date: 11/11/2000 18:41:38 ******/
/****** Object:  Stored Procedure dbo.SP_ATUALIZA_MATRICULA    Script Date: 03/07/99 10:54:18 ******/
/****** Object:  Stored Procedure dbo.SP_ATUALIZA_MATRICULA    Script Date: 07/06/99 20:35:11 ******/
/****** Object:  Stored Procedure dbo.SP_ATUALIZA_MATRICULA    Script Date: 13/04/99 10:43:51 ******/
/****** Object:  Stored Procedure dbo.SP_ATUALIZA_MATRICULA    Script Date: 10/03/99 13:10:25 ******/
/****** Object:  Stored Procedure dbo.SP_ATUALIZA_MATRICULA    Script Date: 08/03/1999 20:04:13 ******/
/****** Object:  Stored Procedure dbo.SP_ATUALIZA_MATRICULA    Script Date: 06/03/99 13:07:52 ******/
ALTER PROCEDURE [dbo].[SP_ATUALIZA_MATRICULA]
@SEQ_TURMA		INTEGER		,
@CD_MATRICULA		INTEGER		,
@SEQ_DEPENDENTE		SMALLINT	,
@CD_CATEGORIA    	SMALLINT	,
@CD_SIT_MATRICULA_ATUAL	CHAR(2)		,
@CD_SIT_MATRICULA_NOVA	CHAR(2)		,
@USER_ACESSO		VARCHAR(12)

AS
INSERT
	TB_HISTORICO_SIT_MATRICULA
	(
	CD_MATRICULA,
	SEQ_DEPENDENTE,
	CD_CATEGORIA,
	SEQ_TURMA,
	DT_HISTORICO_SIT_MATRICULA,
	CD_HISTORICO_SIT_MATRICULA,
	DESCR_HIST_SIT_MATRICULA,
	USER_ACESSO_SISTEMA
	)
VALUES
       (@CD_MATRICULA		,
	@SEQ_DEPENDENTE		,
	@CD_CATEGORIA		,
	@SEQ_TURMA		,
	GETDATE()		,
	@CD_SIT_MATRICULA_NOVA	,
	NULL			,
	@USER_ACESSO)
	
UPDATE
	TB_MATRICULA_CURSO
SET
	CD_SIT_MATRICULA	= @CD_SIT_MATRICULA_NOVA,
	DT_OCORRENCIA_SITUACAO	= GETDATE()
WHERE
	CD_MATRICULA		= @CD_MATRICULA
  AND	SEQ_DEPENDENTE		= @SEQ_DEPENDENTE
  AND	CD_CATEGORIA		= @CD_CATEGORIA
  AND	SEQ_TURMA		= @SEQ_TURMA

IF @CD_SIT_MATRICULA_NOVA = 'NO' 
	EXEC SP_DIMINUI_VAGA_TURMA @SEQ_TURMA
ELSE
	EXEC SP_AUMENTA_VAGA_TURMA @SEQ_TURMA



EXEC SP_ATUALIZA_DESCONTO_FAMILIA @CD_MATRICULA, @CD_CATEGORIA
go

DROP TABLE [dbo].[TB_SERVICO_ACADEMIA]
GO
CREATE TABLE [dbo].[TB_SERVICO_ACADEMIA]
(
	[NU_SEQ_SERVICO] [smallint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[DE_SERVICO] [varchar](40) NOT NULL,
	[QT_ALUNO] [smallint] NOT NULL,
	[QT_LIMITE_SOCIO] [smallint] NULL,
	[QT_DIAS_LIMITE_SOCIO] [smallint] NULL,
	[QT_DIAS_ANT_CLUBE] [smallint] NULL,
	[QT_MIN_ATENDIMENTO] [smallint] NOT NULL,
	[QT_MIN_INTERVALO] [smallint] NULL,
	[VR_MULTA] [money] NULL,
	[CD_TX_MULTA] [smallint] NULL,
	[VR_SERVICO] [money] NULL,
	[CD_TX_SERVICO] [smallint] NULL,
	[PZ_CANCELAMENTO] [smallint] NULL,
	[TP_PRAZO_CANCELAMENTO] [char](1) NULL,
	[IC_AGENDA_INTERNET] [char](1) NULL,
	[QT_DIAS_ANT_INTERNET] [smallint] NULL,
	[IC_SITUACAO] [char](1) NOT NULL,
	[DT_INICIO_VIGENCIA] [datetime] NULL,
	[DT_FIM_VIGENCIA] [datetime] NULL,
)
GO	
DROP TABLE TB_PROFISSIONAL_SERV_ACADEMIA
GO
CREATE TABLE TB_PROFISSIONAL_SERV_ACADEMIA
	(
	NU_SEQ_PROFISSIONAL		INT				IDENTITY NOT NULL PRIMARY KEY,
	NU_SEQ_SERVICO			SMALLINT		NOT NULL ,
	CD_FUNCIONARIO			SMALLINT		NOT NULL ,
	DT_INICIO_VGENCIA		DATETIME		NOT NULL ,
	DT_FIM_VGENCIA			DATETIME		NOT NULL 
	)
GO	
DROP TABLE TB_AGENDA_PROF_ACADEMIA
GO
CREATE TABLE TB_AGENDA_PROF_ACADEMIA
	(
	NU_SEQ_AGENDA			INT				IDENTITY NOT NULL PRIMARY KEY,
	NU_SEQ_PROFISSIONAL		INT				NOT NULL,
	CD_DIA					SMALLINT		NOT NULL,
	HH_INICIO				CHAR(4)			NOT NULL,
	HH_FIM					CHAR(4)			NOT NULL,
	
	)
GO
DROP TABLE TB_AGENDAMENTO_SERV_ACAD
GO
CREATE TABLE TB_AGENDAMENTO_SERV_ACAD
	(
	NU_SEQ_AGENDAMENTO		INT				IDENTITY NOT NULL PRIMARY KEY,
	CD_MATRICULA			INT				NOT NULL,
	CD_CATEGORIA			SMALLINT		NOT NULL,
	SEQ_DEPENDENTE			SMALLINT		NOT NULL,
	NU_SEQ_AGENDA			INT				NOT NULL,
	CD_SITUACAO				CHAR(1)			NOT NULL,
	DT_AGENDAMENTO			DATETIME		NOT NULL,
	USER_AGENDAMENTO		CHAR(12)		NOT NULL,
	DT_CANCELAMENTO			DATETIME		NULL,
	USER_CANCELAMENTO		CHAR(12)		NULL,
	IC_COMPARECIMENTO		CHAR(1)			NULL
	)
GO	
DROP TABLE TB_EXCESSAO_AGENDA_SER_ACAD
GO
CREATE TABLE TB_EXCESSAO_AGENDA_SER_ACAD
	(
	NU_SEQ_EXCESSAO			INT				IDENTITY NOT NULL PRIMARY KEY,
	IC_TIPO					CHAR(1)			NOT NULL,
	NU_SEQ_SERVICO			SMALLINT		NULL,
	CD_FUNCIONARIO			SMALLINT		NULL,
	CD_DIA					SMALLINT		NULL,
	HH_INICIO				CHAR(4)			NULL,
	HH_FIM					CHAR(1)			NULL           
	
	)	
GO
CREATE TABLE [dbo].[TB_LOCAL_ACADEMIA](
	[CD_LOCAL] [smallint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[DESCR_LOCAL] [varchar](30) NOT NULL,
)


